### ISSUE TITLE
Don't work after refresh

### ISSUE THREAD

**Issue by danimesq** [miguelmota/battery#1]

**Comment by miguelmota** [comment]
I haven't been able to reproduce, as seen in screencast:

![reload](https://cloud.githubusercontent.com/assets/168240/14768813/5a0d3940-0a00-11e6-94a4-122e974c8b7b.gif)

If you know the exact steps to reproduce, please reopen issue!

**Comment by danimesq** [comment]
Ok, I'ill try it.

**Comment by danimesq** [comment]
Is quite simple to reproduce it.
1. Go to http://battery.moogs.io/demo/
2. Close and reopen from history

You will see that isn't working after refres: is the same issue I has but with other perspective.
I'm currently using Google Chrome 49.0.2623.112.

**Comment by danimesq** [comment]
If you get the same issue after reproduce these steps, please reopen issue (as reporter I can't do it).

**Comment by danimesq** [comment]
@miguelmota.
