### ISSUE TITLE
Battery Icon in SVG for free resize

### ISSUE THREAD

**Issue by danimesq** [miguelmota/battery#2]

**Comment by miguelmota** [comment]
Resize can be done with percentage based width in CSS. Closing this since it seems unnecessary.

**Comment by danimesq** [comment]
Unnecessary?! I've not talked about the porcentage, I've talked about all the BATTERY ICON!
People that want insert don't need brick head by changing piece by piece for change width and height, if can be used SVG.

**Comment by miguelmota** [comment]
Feel free to fork it and submit a PR. The battery symbol was only meant for the example demo.

**Comment by danimesq** [comment]
@miguelmota, done in #3 pull request.

**Comment by miguelmota** [comment]
I decided to leave this as is. Branch with SVG icon is [here](https://github.com/miguelmota/battery/tree/svg_battery_icon). Fork and do whatever you like. Thanks for your contribution.

**Comment by danimesq** [comment]
People will like more if you converts the original image and use only one branch for it.

**Comment by danimesq** [comment]
"Feel free to fork it and submit a PR. The battery symbol was only meant for the example demo."
I've do the work for you, and you've rejected. Ok, now I've updated the icon and its very better, wich don't justificates now to close issue/PR or create a separate branch for the Scalable Vector Graphic icon.

**Comment by danimesq** [comment]
@miguelmota.
