### ISSUE TITLE
Conflict/Can't work with jQuery included in project

### ISSUE THREAD

**Issue by danimesq** [miguelmota/battery#4]
You can know more here: https://github.com/Software-js/WS.js/issues/248#issuecomment-215541731

**Comment by miguelmota** [comment]
Resolved

**Comment by danimesq** [comment]
You've not referenced a commit to this issue, and/or not referenced the commit on this issue. The two ways are the same and needed on a collaborative community.

**Comment by danimesq** [comment]
You can close an issue directly from a commit, by simple typing title "fixed #4".
"wrapp in iife" and "remove line" are not clear titles for commits and don't explain whats happening, introducting and/or fixing.
Other thing, you're wanting remove my marks in this repository. I've comment my closed issue and pull request, which are closed but currently active. This isn't correct to your contributors.
